spring:
  config:
    import: mySecrets.properties
  datasource:
    url: ${database_url}
    username: ${username}
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /api/v1